openapi: 3.0.3
info:
  title: Swagger Mercadona API
  version: 0.0.0
paths:
  /products/:
    get:
      operationId: products_list
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
    post:
      operationId: products_create
      tags:
      - products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /products/{id}/:
    get:
      operationId: products_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Produit.
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    put:
      operationId: products_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Produit.
        required: true
      tags:
      - products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    patch:
      operationId: products_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Produit.
        required: true
      tags:
      - products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    delete:
      operationId: products_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Produit.
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /promotions/:
    get:
      operationId: promotions_list
      tags:
      - promotions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promotion'
          description: ''
    post:
      operationId: promotions_create
      tags:
      - promotions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Promotion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Promotion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Promotion'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
          description: ''
  /promotions/{id}/:
    get:
      operationId: promotions_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Promotion.
        required: true
      tags:
      - promotions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
          description: ''
    put:
      operationId: promotions_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Promotion.
        required: true
      tags:
      - promotions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Promotion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Promotion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Promotion'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
          description: ''
    patch:
      operationId: promotions_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Promotion.
        required: true
      tags:
      - promotions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPromotion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPromotion'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPromotion'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promotion'
          description: ''
    delete:
      operationId: promotions_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this Promotion.
        required: true
      tags:
      - promotions
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedProduct:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product_title:
          type: string
          title: Nom du produit
          maxLength: 30
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          title: Prix
        sale_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
          title: Prix soldé
        price_before_discount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
          title: Prix initial
        image:
          type: string
          format: uri
          nullable: true
          title: Photo
        creation_date:
          type: string
          format: date-time
          readOnly: true
        category:
          type: integer
          title: Catéguorie
    PatchedPromotion:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_date:
          type: string
          format: date
          title: Date de début
        end_date:
          type: string
          format: date
          title: Date de fin
        discount_percentage:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
          title: Pourcentage de remise
        product:
          type: integer
          title: Nom du produit
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product_title:
          type: string
          title: Nom du produit
          maxLength: 30
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          title: Prix
        sale_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
          title: Prix soldé
        price_before_discount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
          title: Prix initial
        image:
          type: string
          format: uri
          nullable: true
          title: Photo
        creation_date:
          type: string
          format: date-time
          readOnly: true
        category:
          type: integer
          title: Catéguorie
      required:
      - category
      - creation_date
      - id
      - price
      - product_title
    Promotion:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_date:
          type: string
          format: date
          title: Date de début
        end_date:
          type: string
          format: date
          title: Date de fin
        discount_percentage:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
          title: Pourcentage de remise
        product:
          type: integer
          title: Nom du produit
      required:
      - discount_percentage
      - id
      - product
      - start_date
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
