# Generated by Django 4.2.5 on 2023-10-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Catéguorie",
                "verbose_name_plural": "Catéguories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promotion", "verbose_name_plural": "Promotions"},
        ),
        migrations.AlterField(
            model_name="category",
            name="category_title",
            field=models.CharField(max_length=100, verbose_name="Catéguorie"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Catéguorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_title",
            field=models.CharField(max_length=200, verbose_name="Nom du produit"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Pourcentage de la remise"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Nom du produit",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateField(verbose_name="Date de début"),
        ),
    ]
