# Generated by Django 4.2.5 on 2023-10-08 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_category_category_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 19, 15, 34, 309481)
            ),
        ),
    ]
