# Generated by Django 4.2.5 on 2023-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_product_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
