# Generated by Django 4.2.5 on 2023-10-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_product_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(blank=True, verbose_name="Date de fin"),
        ),
    ]
