# Generated by Django 4.2.6 on 2023-10-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_description_alter_promotion_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_promotion",
            field=models.BooleanField(default=False, verbose_name="En promotion"),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin de promotion"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_percentage",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Pourcentage de promotion"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de début de promotion"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Catégorie",
            ),
        ),
    ]
