# Generated by Django 4.2.6 on 2023-10-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_product_is_promotion_product_promotion_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_promotion",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotion_end_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotion_percentage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotion_start_date",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Catéguorie",
            ),
        ),
    ]
