# Generated by Django 4.2.6 on 2023-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_product_is_promotion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix soldé",
            ),
        ),
    ]
