# Generated by Django 4.2.6 on 2023-10-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_product_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_before_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix avant la remise",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Catégorie",
            ),
        ),
    ]
