# Generated by Django 4.2.6 on 2023-10-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_product_price_before_discount_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Catéguorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_before_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix initial",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Pourcentage de remise"
            ),
        ),
    ]
