# Generated by Django 4.2.6 on 2023-10-13 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Pourcentage de remise",
            ),
        ),
    ]
