# Generated by Django 4.2.6 on 2023-10-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="photo.jpg",
                null=True,
                upload_to="media/images/",
                verbose_name="Photo",
            ),
        ),
    ]
