# Generated by Django 4.2.6 on 2023-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_before_discount",
        ),
    ]
