# Generated by Django 4.2.6 on 2023-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_remove_product_price_before_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_before_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix initial",
            ),
        ),
    ]
